---
- hosts: multi
  become: true
  roles:
          - andrewrothstein.epel
  tasks:
          - name: install nrpe
            yum:
                    name: ['nrpe', 'nagios-plugins-nrpe','nagios-plugins-ping', 'nagios-plugins-disk' , 'nagios-plugins-users','nagios-plugins-procs','nagios-plugins-load','nagios-plugins-swap','nagios-plugins-ssh','nagios-plugins-http']
                    enablerepo: epel
                    state: present
            become: true


          - name: set nrpe.cfg
            become: true
            template:
                    src: files/nrpe/nrpe.j2
                    dest: /etc/nagios/nrpe.cfg
                    owner: root
                    group: nagios 
                    mode: 0644



          - name: set nrpe plugins
            become: true
            copy:
                    src: files/nrpe/plugins/
                    dest: /usr/lib64/nagios/plugins/
                    owner: root
                    group: root
                    mode: 0777
         
          - name: nrpe
            become: true
            systemd: name=nrpe state=restarted enabled=yes
         
- hosts: nagios
  vars_files:
          - vars/credentials.yml
  become: true
  tasks:
          - name: install nagios
            yum:
                    name: ['nagios', 'nagios-plugins-ping', 'nagios-plugins-disk' , 'nagios-plugins-users','nagios-plugins-procs','nagios-plugins-load','nagios-plugins-swap','nagios-plugins-ssh','nagios-plugins-http']
                    enablerepo: epel
                    state: present
            become: true
          
          - name: set nagios.conf files
            become: true
            copy:
                    src: files/nagios/nagios.conf
                    dest: /etc/httpd/conf.d/nagios.conf
                    owner: root
                    group: root
                    mode: 0644

          - name: set nagios.cfg files
            become: true
            copy:
                    src: files/nagios/nagios.cfg
                    dest: /etc/nagios/nagios.cfg
                    owner: root
                    group: nagios
                    mode: 0664

          - name: Check nagios Users
            stat: path=/etc/nagios/passwd
            register: nagios_user_pwfile_exists
            become: true

          - name: add nagios admin user
            command: "htpasswd -b -c /etc/nagios/passwd nagiosadmin {{ nagios_passwd }}"
            become: true
            when: nagios_user_pwfile_exists != 0

          - name: mkdir servers
            file:
                    dest: /etc/nagios/servers
                    mode: 0750
                    group: nagios
                    state: directory

                    ####this should be the ip and name from a node
          - name: set generic servers file
            template:
                     src: files/nagios/node01.j2
                     dest: /etc/nagios/servers/generic.cfg
                     group: nagios

          - name: set commands
            become: true
            copy:
                    src: files/nagios/commands.cfg
                    dest: /etc/nagios/objects/commands.cfg
                    owner: root
                    group: root
                    mode: 0664
          - name: restart nagios 
            become: true
            systemd: name=nagios state=restarted enabled=yes
            
          - name: restart httpd 
            become: true
            systemd: name=httpd state=restarted enabled=yes
          
